# -*- coding: utf-8 -*-
"""Public QGIS-free grid API."""

from .distance import local_distance_crs
from .arrays import (
    axis_resolution,
    assert_header_file_matches,
    assert_matches_header,
    assert_netcdf_matches_header,
    assert_source_covers_header,
    axes_match_header,
    ensure_latitude_descending,
    force_target_grid,
    grid_matches_header,
    header_from_coordinate_axes,
    header_center_arrays,
    mesh_resolution,
    nearest_curvilinear,
    nearest_rectilinear,
    normalize_spatial_axes,
    reindex_to_header,
    resample_to_target_grid,
    resample_to_target_points,
    slice_and_pad,
    snap_bounds_to_grid,
    subset_dataset,
    target_grid_from_header,
)
from .model import (
    Extent,
    Grid,
    NODATA_VALUE,
    Resolution,
    SpatialResolution,
    TargetGrid,
    aligned_window,
    aligned_l0_l2_headers,
    alignment_gap,
    alignment_gap_limit_fraction,
    ceil_cellsize,
    cellsize_precision_for_unit,
    crs_equal,
    display_precision_for_unit,
    floor_cellsize,
    floor_to_precision,
    format_resolution,
    geotransform_bounds,
    geotransform_from_header,
    header_bounds,
    header_center_coordinates,
    header_from_geotransform,
    header_for_aligned_bounds,
    header_for_bounds,
    header_for_existing_bounds,
    integer_resolution_factor,
    is_geographic_unit,
    l0_header_from_l2,
    nearest_integer_multiple,
    north_up_cellsize,
    possible_resolutions,
    read_header_file,
    raster_resolution_info,
    resolution_in_crs,
    resolution_is_multiple,
    raster_grids_match,
    standardize_header,
    headers_match,
    validate_l0_l2_alignment,
    validate_grid_headers,
    write_header_file,
)

__all__ = [name for name in globals() if not name.startswith("_")]
