# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymhm/ui/discharge_table_assignment_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DischargeTableAssignmentDialog(object):
    def setupUi(self, DischargeTableAssignmentDialog):
        DischargeTableAssignmentDialog.setObjectName("DischargeTableAssignmentDialog")
        DischargeTableAssignmentDialog.resize(560, 320)
        self.verticalLayout = QtWidgets.QVBoxLayout(DischargeTableAssignmentDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.intro_label = QtWidgets.QLabel(DischargeTableAssignmentDialog)
        self.intro_label.setWordWrap(True)
        self.intro_label.setObjectName("intro_label")
        self.verticalLayout.addWidget(self.intro_label)
        self.scroll_area = QtWidgets.QScrollArea(DischargeTableAssignmentDialog)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.rows_widget = QtWidgets.QWidget()
        self.rows_widget.setGeometry(QtCore.QRect(0, 0, 534, 234))
        self.rows_widget.setObjectName("rows_widget")
        self.rows_layout = QtWidgets.QGridLayout(self.rows_widget)
        self.rows_layout.setObjectName("rows_layout")
        self.rows_layout.setColumnStretch(1, 1)
        self.scroll_area.setWidget(self.rows_widget)
        self.verticalLayout.addWidget(self.scroll_area)
        self.buttons = QtWidgets.QDialogButtonBox(DischargeTableAssignmentDialog)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(DischargeTableAssignmentDialog)
        self.buttons.accepted.connect(DischargeTableAssignmentDialog.accept) # type: ignore
        self.buttons.rejected.connect(DischargeTableAssignmentDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DischargeTableAssignmentDialog)

    def retranslateUi(self, DischargeTableAssignmentDialog):
        _translate = QtCore.QCoreApplication.translate
        DischargeTableAssignmentDialog.setWindowTitle(_translate("DischargeTableAssignmentDialog", "Assign Discharge Tables"))
        self.intro_label.setText(_translate("DischargeTableAssignmentDialog", "Select one discharge table layer for each STATION_ID."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DischargeTableAssignmentDialog = QtWidgets.QDialog()
    ui = Ui_DischargeTableAssignmentDialog()
    ui.setupUi(DischargeTableAssignmentDialog)
    DischargeTableAssignmentDialog.show()
    sys.exit(app.exec_())
