# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymhm/ui/elevation_band_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ElevationBandDialog(object):
    def setupUi(self, ElevationBandDialog):
        ElevationBandDialog.setObjectName("ElevationBandDialog")
        ElevationBandDialog.resize(360, 170)
        self.verticalLayout = QtWidgets.QVBoxLayout(ElevationBandDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_minElevation = QtWidgets.QLabel(ElevationBandDialog)
        self.label_minElevation.setObjectName("label_minElevation")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_minElevation)
        self.min_elevation_value = QtWidgets.QLabel(ElevationBandDialog)
        self.min_elevation_value.setObjectName("min_elevation_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.min_elevation_value)
        self.label_maxElevation = QtWidgets.QLabel(ElevationBandDialog)
        self.label_maxElevation.setObjectName("label_maxElevation")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_maxElevation)
        self.max_elevation_value = QtWidgets.QLabel(ElevationBandDialog)
        self.max_elevation_value.setObjectName("max_elevation_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.max_elevation_value)
        self.label_width = QtWidgets.QLabel(ElevationBandDialog)
        self.label_width.setObjectName("label_width")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_width)
        self.width_spin_box = QtWidgets.QDoubleSpinBox(ElevationBandDialog)
        self.width_spin_box.setDecimals(3)
        self.width_spin_box.setMinimum(0.001)
        self.width_spin_box.setObjectName("width_spin_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.width_spin_box)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttons = QtWidgets.QDialogButtonBox(ElevationBandDialog)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(ElevationBandDialog)
        self.buttons.accepted.connect(ElevationBandDialog.accept) # type: ignore
        self.buttons.rejected.connect(ElevationBandDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ElevationBandDialog)

    def retranslateUi(self, ElevationBandDialog):
        _translate = QtCore.QCoreApplication.translate
        ElevationBandDialog.setWindowTitle(_translate("ElevationBandDialog", "Elevation Bands"))
        self.label_minElevation.setText(_translate("ElevationBandDialog", "Selected DEM minimum:"))
        self.min_elevation_value.setText(_translate("ElevationBandDialog", "0.00"))
        self.label_maxElevation.setText(_translate("ElevationBandDialog", "Selected DEM maximum:"))
        self.max_elevation_value.setText(_translate("ElevationBandDialog", "0.00"))
        self.label_width.setText(_translate("ElevationBandDialog", "Elevation window width:"))
