# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymhm/ui/lookup_config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LookupConfigDialog(object):
    def setupUi(self, LookupConfigDialog):
        LookupConfigDialog.setObjectName("LookupConfigDialog")
        LookupConfigDialog.resize(480, 190)
        self.formLayout = QtWidgets.QFormLayout(LookupConfigDialog)
        self.formLayout.setObjectName("formLayout")
        self.label_lookupTable = QtWidgets.QLabel(LookupConfigDialog)
        self.label_lookupTable.setObjectName("label_lookupTable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_lookupTable)
        self.lookup_table_combo = QtWidgets.QComboBox(LookupConfigDialog)
        self.lookup_table_combo.setObjectName("lookup_table_combo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lookup_table_combo)
        self.label_mappingField = QtWidgets.QLabel(LookupConfigDialog)
        self.label_mappingField.setObjectName("label_mappingField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_mappingField)
        self.mapping_field_combo = QtWidgets.QComboBox(LookupConfigDialog)
        self.mapping_field_combo.setObjectName("mapping_field_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mapping_field_combo)
        self.label_classField = QtWidgets.QLabel(LookupConfigDialog)
        self.label_classField.setObjectName("label_classField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_classField)
        self.class_field_combo = QtWidgets.QComboBox(LookupConfigDialog)
        self.class_field_combo.setObjectName("class_field_combo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.class_field_combo)
        self.error_label = QtWidgets.QLabel(LookupConfigDialog)
        self.error_label.setText("")
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName("error_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.error_label)
        self.buttons = QtWidgets.QDialogButtonBox(LookupConfigDialog)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.buttons)

        self.retranslateUi(LookupConfigDialog)
        self.buttons.accepted.connect(LookupConfigDialog.accept) # type: ignore
        self.buttons.rejected.connect(LookupConfigDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LookupConfigDialog)

    def retranslateUi(self, LookupConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        LookupConfigDialog.setWindowTitle(_translate("LookupConfigDialog", "Lookup Table"))
        self.label_lookupTable.setText(_translate("LookupConfigDialog", "Lookup table"))
        self.label_mappingField.setText(_translate("LookupConfigDialog", "Mapping field"))
        self.label_classField.setText(_translate("LookupConfigDialog", "Class field"))
