# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymhm/ui/mhm_ready_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleLayerInputDialog(object):
    def setupUi(self, SingleLayerInputDialog):
        SingleLayerInputDialog.setObjectName("SingleLayerInputDialog")
        SingleLayerInputDialog.resize(500, 204)
        self.verticalLayout = QtWidgets.QVBoxLayout(SingleLayerInputDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_inputType = QtWidgets.QGroupBox(SingleLayerInputDialog)
        self.groupBox_inputType.setTitle("")
        self.groupBox_inputType.setObjectName("groupBox_inputType")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_inputType)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_inputLayer = QtWidgets.QHBoxLayout()
        self.horizontalLayout_inputLayer.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_inputLayer.setObjectName("horizontalLayout_inputLayer")
        self.label_inputLayer = QtWidgets.QLabel(self.groupBox_inputType)
        self.label_inputLayer.setObjectName("label_inputLayer")
        self.horizontalLayout_inputLayer.addWidget(self.label_inputLayer)
        self.comboBox_inputLayer = QtWidgets.QComboBox(self.groupBox_inputType)
        self.comboBox_inputLayer.setObjectName("comboBox_inputLayer")
        self.horizontalLayout_inputLayer.addWidget(self.comboBox_inputLayer)
        self.pushButton_browseInputLayer = QtWidgets.QPushButton(self.groupBox_inputType)
        self.pushButton_browseInputLayer.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_browseInputLayer.setObjectName("pushButton_browseInputLayer")
        self.horizontalLayout_inputLayer.addWidget(self.pushButton_browseInputLayer)
        self.horizontalLayout_inputLayer.setStretch(0, 1)
        self.horizontalLayout_inputLayer.setStretch(1, 2)
        self.horizontalLayout_inputLayer.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_inputLayer)
        self.horizontalLayout_classDefinition = QtWidgets.QHBoxLayout()
        self.horizontalLayout_classDefinition.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_classDefinition.setObjectName("horizontalLayout_classDefinition")
        self.label_classDefinition = QtWidgets.QLabel(self.groupBox_inputType)
        self.label_classDefinition.setEnabled(False)
        self.label_classDefinition.setObjectName("label_classDefinition")
        self.horizontalLayout_classDefinition.addWidget(self.label_classDefinition)
        self.comboBox_classDefinitionInput = QtWidgets.QComboBox(self.groupBox_inputType)
        self.comboBox_classDefinitionInput.setEnabled(False)
        self.comboBox_classDefinitionInput.setObjectName("comboBox_classDefinitionInput")
        self.horizontalLayout_classDefinition.addWidget(self.comboBox_classDefinitionInput)
        self.pushButton_browseClassDefinition = QtWidgets.QPushButton(self.groupBox_inputType)
        self.pushButton_browseClassDefinition.setEnabled(False)
        self.pushButton_browseClassDefinition.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_browseClassDefinition.setObjectName("pushButton_browseClassDefinition")
        self.horizontalLayout_classDefinition.addWidget(self.pushButton_browseClassDefinition)
        self.horizontalLayout_classDefinition.setStretch(0, 1)
        self.horizontalLayout_classDefinition.setStretch(1, 2)
        self.horizontalLayout_classDefinition.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_classDefinition)
        self.verticalLayout.addWidget(self.groupBox_inputType)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttons = QtWidgets.QDialogButtonBox(SingleLayerInputDialog)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(SingleLayerInputDialog)
        self.buttons.accepted.connect(SingleLayerInputDialog.accept) # type: ignore
        self.buttons.rejected.connect(SingleLayerInputDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SingleLayerInputDialog)

    def retranslateUi(self, SingleLayerInputDialog):
        _translate = QtCore.QCoreApplication.translate
        SingleLayerInputDialog.setWindowTitle(_translate("SingleLayerInputDialog", "Lookup Table"))
        self.label_inputLayer.setText(_translate("SingleLayerInputDialog", "mHM Ready Input:"))
        self.pushButton_browseInputLayer.setToolTip(_translate("SingleLayerInputDialog", "Select Project Folder"))
        self.pushButton_browseInputLayer.setText(_translate("SingleLayerInputDialog", "..."))
        self.label_classDefinition.setText(_translate("SingleLayerInputDialog", "Class Definition:"))
        self.pushButton_browseClassDefinition.setToolTip(_translate("SingleLayerInputDialog", "Select Project Folder"))
        self.pushButton_browseClassDefinition.setText(_translate("SingleLayerInputDialog", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SingleLayerInputDialog = QtWidgets.QDialog()
    ui = Ui_SingleLayerInputDialog()
    ui.setupUi(SingleLayerInputDialog)
    SingleLayerInputDialog.show()
    sys.exit(app.exec_())
