# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymhm/ui/project_terminal_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectTerminalDialog(object):
    def setupUi(self, ProjectTerminalDialog):
        ProjectTerminalDialog.setObjectName("ProjectTerminalDialog")
        ProjectTerminalDialog.resize(900, 520)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProjectTerminalDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output = QtWidgets.QPlainTextEdit(ProjectTerminalDialog)
        self.output.setReadOnly(True)
        self.output.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.command_row = QtWidgets.QHBoxLayout()
        self.command_row.setObjectName("command_row")
        self.command_edit = QtWidgets.QLineEdit(ProjectTerminalDialog)
        self.command_edit.setObjectName("command_edit")
        self.command_row.addWidget(self.command_edit)
        self.send_button = QtWidgets.QPushButton(ProjectTerminalDialog)
        self.send_button.setObjectName("send_button")
        self.command_row.addWidget(self.send_button)
        self.clear_button = QtWidgets.QPushButton(ProjectTerminalDialog)
        self.clear_button.setObjectName("clear_button")
        self.command_row.addWidget(self.clear_button)
        self.close_button = QtWidgets.QPushButton(ProjectTerminalDialog)
        self.close_button.setObjectName("close_button")
        self.command_row.addWidget(self.close_button)
        self.verticalLayout.addLayout(self.command_row)

        self.retranslateUi(ProjectTerminalDialog)
        QtCore.QMetaObject.connectSlotsByName(ProjectTerminalDialog)

    def retranslateUi(self, ProjectTerminalDialog):
        _translate = QtCore.QCoreApplication.translate
        ProjectTerminalDialog.setWindowTitle(_translate("ProjectTerminalDialog", "Project Terminal"))
        self.command_edit.setPlaceholderText(_translate("ProjectTerminalDialog", "Command"))
        self.send_button.setText(_translate("ProjectTerminalDialog", "Run"))
        self.clear_button.setText(_translate("ProjectTerminalDialog", "Clear"))
        self.close_button.setText(_translate("ProjectTerminalDialog", "Close"))
