# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/discharge_table_assignment_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DischargeTableAssignmentDialog(object):
    def setupUi(self, DischargeTableAssignmentDialog):
        DischargeTableAssignmentDialog.setObjectName("DischargeTableAssignmentDialog")
        DischargeTableAssignmentDialog.resize(678, 488)
        self.verticalLayout = QtWidgets.QVBoxLayout(DischargeTableAssignmentDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.intro_label = QtWidgets.QLabel(DischargeTableAssignmentDialog)
        self.intro_label.setWordWrap(True)
        self.intro_label.setObjectName("intro_label")
        self.verticalLayout.addWidget(self.intro_label)
        self.scroll_area = QtWidgets.QScrollArea(DischargeTableAssignmentDialog)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.rows_widget = QtWidgets.QWidget()
        self.rows_widget.setGeometry(QtCore.QRect(0, 0, 658, 410))
        self.rows_widget.setObjectName("rows_widget")
        self.rows_layout = QtWidgets.QGridLayout(self.rows_widget)
        self.rows_layout.setObjectName("rows_layout")
        self.label_pourPointIDValue = QtWidgets.QLabel(self.rows_widget)
        self.label_pourPointIDValue.setText("")
        self.label_pourPointIDValue.setObjectName("label_pourPointIDValue")
        self.rows_layout.addWidget(self.label_pourPointIDValue, 0, 1, 1, 1)
        self.label_pourPointID = QtWidgets.QLabel(self.rows_widget)
        self.label_pourPointID.setObjectName("label_pourPointID")
        self.rows_layout.addWidget(self.label_pourPointID, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rows_layout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_browseDischargeTable1 = QtWidgets.QPushButton(self.rows_widget)
        self.pushButton_browseDischargeTable1.setEnabled(False)
        self.pushButton_browseDischargeTable1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_browseDischargeTable1.setObjectName("pushButton_browseDischargeTable1")
        self.rows_layout.addWidget(self.pushButton_browseDischargeTable1, 0, 4, 1, 1)
        self.comboBox_dischargeTableInput = QtWidgets.QComboBox(self.rows_widget)
        self.comboBox_dischargeTableInput.setEnabled(False)
        self.comboBox_dischargeTableInput.setObjectName("comboBox_dischargeTableInput")
        self.rows_layout.addWidget(self.comboBox_dischargeTableInput, 0, 3, 1, 1)
        self.checkBox_isGauge = QtWidgets.QCheckBox(self.rows_widget)
        self.checkBox_isGauge.setObjectName("checkBox_isGauge")
        self.rows_layout.addWidget(self.checkBox_isGauge, 0, 2, 1, 1)
        self.rows_layout.setColumnStretch(0, 2)
        self.rows_layout.setColumnStretch(1, 1)
        self.rows_layout.setColumnStretch(2, 2)
        self.rows_layout.setColumnStretch(3, 5)
        self.rows_layout.setColumnStretch(4, 1)
        self.scroll_area.setWidget(self.rows_widget)
        self.verticalLayout.addWidget(self.scroll_area)
        self.buttons = QtWidgets.QDialogButtonBox(DischargeTableAssignmentDialog)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(DischargeTableAssignmentDialog)
        self.buttons.accepted.connect(DischargeTableAssignmentDialog.accept) # type: ignore
        self.buttons.rejected.connect(DischargeTableAssignmentDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DischargeTableAssignmentDialog)

    def retranslateUi(self, DischargeTableAssignmentDialog):
        _translate = QtCore.QCoreApplication.translate
        DischargeTableAssignmentDialog.setWindowTitle(_translate("DischargeTableAssignmentDialog", "Assign Discharge Tables"))
        self.intro_label.setText(_translate("DischargeTableAssignmentDialog", "Select one discharge table layer for each STATION_ID."))
        self.label_pourPointID.setText(_translate("DischargeTableAssignmentDialog", "Pour Point ID:"))
        self.pushButton_browseDischargeTable1.setToolTip(_translate("DischargeTableAssignmentDialog", "Select Project Folder"))
        self.pushButton_browseDischargeTable1.setText(_translate("DischargeTableAssignmentDialog", "..."))
        self.checkBox_isGauge.setText(_translate("DischargeTableAssignmentDialog", "Is Gauge?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DischargeTableAssignmentDialog = QtWidgets.QDialog()
    ui = Ui_DischargeTableAssignmentDialog()
    ui.setupUi(DischargeTableAssignmentDialog)
    DischargeTableAssignmentDialog.show()
    sys.exit(app.exec_())
