# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/thread_display_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThreadDisplayDialog(object):
    def setupUi(self, ThreadDisplayDialog):
        ThreadDisplayDialog.setObjectName("ThreadDisplayDialog")
        ThreadDisplayDialog.resize(720, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(ThreadDisplayDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_threads = QtWidgets.QHBoxLayout()
        self.horizontalLayout_threads.setObjectName("horizontalLayout_threads")
        self.label_threadCount = QtWidgets.QLabel(ThreadDisplayDialog)
        self.label_threadCount.setObjectName("label_threadCount")
        self.horizontalLayout_threads.addWidget(self.label_threadCount)
        self.spinBox_threadCount = QtWidgets.QSpinBox(ThreadDisplayDialog)
        self.spinBox_threadCount.setMinimum(1)
        self.spinBox_threadCount.setMaximum(32)
        self.spinBox_threadCount.setProperty("value", 2)
        self.spinBox_threadCount.setObjectName("spinBox_threadCount")
        self.horizontalLayout_threads.addWidget(self.spinBox_threadCount)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_threads.addItem(spacerItem)
        self.pushButton_addNThreads = QtWidgets.QPushButton(ThreadDisplayDialog)
        self.pushButton_addNThreads.setMinimumSize(QtCore.QSize(23, 23))
        self.pushButton_addNThreads.setMaximumSize(QtCore.QSize(23, 16777215))
        self.pushButton_addNThreads.setAutoFillBackground(False)
        self.pushButton_addNThreads.setStyleSheet("    QPushButton {\n"
"        text-align: left;\n"
"    }")
        self.pushButton_addNThreads.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/mhm_qgis/Resources/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_addNThreads.setIcon(icon)
        self.pushButton_addNThreads.setObjectName("pushButton_addNThreads")
        self.horizontalLayout_threads.addWidget(self.pushButton_addNThreads)
        self.verticalLayout.addLayout(self.horizontalLayout_threads)
        self.tableWidget_threads = QtWidgets.QTableWidget(ThreadDisplayDialog)
        self.tableWidget_threads.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_threads.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_threads.setObjectName("tableWidget_threads")
        self.tableWidget_threads.setColumnCount(4)
        self.tableWidget_threads.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_threads.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_threads.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_threads.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_threads.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget_threads)
        self.plainTextEdit_threadLog = QtWidgets.QPlainTextEdit(ThreadDisplayDialog)
        self.plainTextEdit_threadLog.setReadOnly(True)
        self.plainTextEdit_threadLog.setObjectName("plainTextEdit_threadLog")
        self.verticalLayout.addWidget(self.plainTextEdit_threadLog)
        self.buttons = QtWidgets.QDialogButtonBox(ThreadDisplayDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(ThreadDisplayDialog)
        self.buttons.rejected.connect(ThreadDisplayDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ThreadDisplayDialog)

    def retranslateUi(self, ThreadDisplayDialog):
        _translate = QtCore.QCoreApplication.translate
        ThreadDisplayDialog.setWindowTitle(_translate("ThreadDisplayDialog", "Plugin Tasks"))
        self.label_threadCount.setText(_translate("ThreadDisplayDialog", "Worker threads:"))
        self.pushButton_addNThreads.setToolTip(_translate("ThreadDisplayDialog", "Execute All Morphology"))
        item = self.tableWidget_threads.horizontalHeaderItem(0)
        item.setText(_translate("ThreadDisplayDialog", "Thread"))
        item = self.tableWidget_threads.horizontalHeaderItem(1)
        item.setText(_translate("ThreadDisplayDialog", "Status"))
        item = self.tableWidget_threads.horizontalHeaderItem(2)
        item.setText(_translate("ThreadDisplayDialog", "Task"))
        item = self.tableWidget_threads.horizontalHeaderItem(3)
        item.setText(_translate("ThreadDisplayDialog", "Progress"))
        self.plainTextEdit_threadLog.setPlaceholderText(_translate("ThreadDisplayDialog", "Select a thread to view its log."))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ThreadDisplayDialog = QtWidgets.QDialog()
    ui = Ui_ThreadDisplayDialog()
    ui.setupUi(ThreadDisplayDialog)
    ThreadDisplayDialog.show()
    sys.exit(app.exec_())
