# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/lai_netcdf_input_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleLayerInputDialog(object):
    def setupUi(self, SingleLayerInputDialog):
        SingleLayerInputDialog.setObjectName("SingleLayerInputDialog")
        SingleLayerInputDialog.resize(500, 217)
        self.verticalLayout = QtWidgets.QVBoxLayout(SingleLayerInputDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_inputType = QtWidgets.QGroupBox(SingleLayerInputDialog)
        self.groupBox_inputType.setObjectName("groupBox_inputType")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_inputType)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_laiNetCDFInput = QtWidgets.QHBoxLayout()
        self.horizontalLayout_laiNetCDFInput.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_laiNetCDFInput.setObjectName("horizontalLayout_laiNetCDFInput")
        self.label_laiNetCDFInput = QtWidgets.QLabel(self.groupBox_inputType)
        self.label_laiNetCDFInput.setObjectName("label_laiNetCDFInput")
        self.horizontalLayout_laiNetCDFInput.addWidget(self.label_laiNetCDFInput)
        self.comboBox_laiNetCDFInput = QtWidgets.QComboBox(self.groupBox_inputType)
        self.comboBox_laiNetCDFInput.setObjectName("comboBox_laiNetCDFInput")
        self.horizontalLayout_laiNetCDFInput.addWidget(self.comboBox_laiNetCDFInput)
        self.pushButton_browseLAINetCDFInput = QtWidgets.QPushButton(self.groupBox_inputType)
        self.pushButton_browseLAINetCDFInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_browseLAINetCDFInput.setObjectName("pushButton_browseLAINetCDFInput")
        self.horizontalLayout_laiNetCDFInput.addWidget(self.pushButton_browseLAINetCDFInput)
        self.horizontalLayout_laiNetCDFInput.setStretch(0, 1)
        self.horizontalLayout_laiNetCDFInput.setStretch(1, 2)
        self.horizontalLayout_laiNetCDFInput.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_laiNetCDFInput)
        self.horizontalLayout_cinputTemporalResolution = QtWidgets.QHBoxLayout()
        self.horizontalLayout_cinputTemporalResolution.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_cinputTemporalResolution.setObjectName("horizontalLayout_cinputTemporalResolution")
        self.label_inputTemporalResolution = QtWidgets.QLabel(self.groupBox_inputType)
        self.label_inputTemporalResolution.setEnabled(True)
        self.label_inputTemporalResolution.setObjectName("label_inputTemporalResolution")
        self.horizontalLayout_cinputTemporalResolution.addWidget(self.label_inputTemporalResolution)
        self.comboBox_inputTemporalResolution = QtWidgets.QComboBox(self.groupBox_inputType)
        self.comboBox_inputTemporalResolution.setEnabled(True)
        self.comboBox_inputTemporalResolution.setObjectName("comboBox_inputTemporalResolution")
        self.comboBox_inputTemporalResolution.addItem("")
        self.comboBox_inputTemporalResolution.addItem("")
        self.comboBox_inputTemporalResolution.addItem("")
        self.comboBox_inputTemporalResolution.addItem("")
        self.comboBox_inputTemporalResolution.addItem("")
        self.comboBox_inputTemporalResolution.addItem("")
        self.horizontalLayout_cinputTemporalResolution.addWidget(self.comboBox_inputTemporalResolution)
        self.horizontalLayout_cinputTemporalResolution.setStretch(0, 1)
        self.horizontalLayout_cinputTemporalResolution.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_cinputTemporalResolution)
        self.horizontalLayout_timestepLAIInput = QtWidgets.QHBoxLayout()
        self.horizontalLayout_timestepLAIInput.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_timestepLAIInput.setObjectName("horizontalLayout_timestepLAIInput")
        self.label_timestepLAIInput = QtWidgets.QLabel(self.groupBox_inputType)
        self.label_timestepLAIInput.setEnabled(True)
        self.label_timestepLAIInput.setObjectName("label_timestepLAIInput")
        self.horizontalLayout_timestepLAIInput.addWidget(self.label_timestepLAIInput)
        self.comboBox_timestepLAIInput = QtWidgets.QComboBox(self.groupBox_inputType)
        self.comboBox_timestepLAIInput.setEnabled(True)
        self.comboBox_timestepLAIInput.setObjectName("comboBox_timestepLAIInput")
        self.comboBox_timestepLAIInput.addItem("")
        self.comboBox_timestepLAIInput.addItem("")
        self.comboBox_timestepLAIInput.addItem("")
        self.comboBox_timestepLAIInput.addItem("")
        self.horizontalLayout_timestepLAIInput.addWidget(self.comboBox_timestepLAIInput)
        self.horizontalLayout_timestepLAIInput.setStretch(0, 1)
        self.horizontalLayout_timestepLAIInput.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_timestepLAIInput)
        self.verticalLayout.addWidget(self.groupBox_inputType)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttons = QtWidgets.QDialogButtonBox(SingleLayerInputDialog)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(SingleLayerInputDialog)
        self.comboBox_inputTemporalResolution.setCurrentIndex(-1)
        self.comboBox_timestepLAIInput.setCurrentIndex(-1)
        self.buttons.accepted.connect(SingleLayerInputDialog.accept) # type: ignore
        self.buttons.rejected.connect(SingleLayerInputDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SingleLayerInputDialog)

    def retranslateUi(self, SingleLayerInputDialog):
        _translate = QtCore.QCoreApplication.translate
        SingleLayerInputDialog.setWindowTitle(_translate("SingleLayerInputDialog", "Lookup Table"))
        self.groupBox_inputType.setTitle(_translate("SingleLayerInputDialog", "LAI"))
        self.label_laiNetCDFInput.setText(_translate("SingleLayerInputDialog", "LAI netcdf input:"))
        self.pushButton_browseLAINetCDFInput.setToolTip(_translate("SingleLayerInputDialog", "Select Project Folder"))
        self.pushButton_browseLAINetCDFInput.setText(_translate("SingleLayerInputDialog", "..."))
        self.label_inputTemporalResolution.setText(_translate("SingleLayerInputDialog", "Temporal Resolution:"))
        self.comboBox_inputTemporalResolution.setItemText(0, _translate("SingleLayerInputDialog", "Daily"))
        self.comboBox_inputTemporalResolution.setItemText(1, _translate("SingleLayerInputDialog", "Semi-weekly"))
        self.comboBox_inputTemporalResolution.setItemText(2, _translate("SingleLayerInputDialog", "Weekly"))
        self.comboBox_inputTemporalResolution.setItemText(3, _translate("SingleLayerInputDialog", "Biweekly"))
        self.comboBox_inputTemporalResolution.setItemText(4, _translate("SingleLayerInputDialog", "Monthly"))
        self.comboBox_inputTemporalResolution.setItemText(5, _translate("SingleLayerInputDialog", "Annual"))
        self.label_timestepLAIInput.setText(_translate("SingleLayerInputDialog", "Timestep LAI input:"))
        self.comboBox_timestepLAIInput.setItemText(0, _translate("SingleLayerInputDialog", "Daily Gridded Data"))
        self.comboBox_timestepLAIInput.setItemText(1, _translate("SingleLayerInputDialog", "Monthly Gridded Data"))
        self.comboBox_timestepLAIInput.setItemText(2, _translate("SingleLayerInputDialog", "Yearly Gridded Data"))
        self.comboBox_timestepLAIInput.setItemText(3, _translate("SingleLayerInputDialog", "Long Term Mean Monthly Gridded Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SingleLayerInputDialog = QtWidgets.QDialog()
    ui = Ui_SingleLayerInputDialog()
    ui.setupUi(SingleLayerInputDialog)
    SingleLayerInputDialog.show()
    sys.exit(app.exec_())
