# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mhm_qgis/ui/single_layer_input_with_lookup_config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleLayerInputDialog(object):
    def setupUi(self, SingleLayerInputDialog):
        SingleLayerInputDialog.setObjectName("SingleLayerInputDialog")
        SingleLayerInputDialog.resize(500, 284)
        self.verticalLayout = QtWidgets.QVBoxLayout(SingleLayerInputDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_inputLayerType = QtWidgets.QGroupBox(SingleLayerInputDialog)
        self.groupBox_inputLayerType.setTitle("")
        self.groupBox_inputLayerType.setObjectName("groupBox_inputLayerType")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_inputLayerType)
        self.verticalLayout_3.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_inputLayer = QtWidgets.QHBoxLayout()
        self.horizontalLayout_inputLayer.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_inputLayer.setObjectName("horizontalLayout_inputLayer")
        self.label_inputLayer = QtWidgets.QLabel(self.groupBox_inputLayerType)
        self.label_inputLayer.setObjectName("label_inputLayer")
        self.horizontalLayout_inputLayer.addWidget(self.label_inputLayer)
        self.comboBox_inputLayer = QtWidgets.QComboBox(self.groupBox_inputLayerType)
        self.comboBox_inputLayer.setObjectName("comboBox_inputLayer")
        self.horizontalLayout_inputLayer.addWidget(self.comboBox_inputLayer)
        self.pushButton_browseInputLayer = QtWidgets.QPushButton(self.groupBox_inputLayerType)
        self.pushButton_browseInputLayer.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_browseInputLayer.setObjectName("pushButton_browseInputLayer")
        self.horizontalLayout_inputLayer.addWidget(self.pushButton_browseInputLayer)
        self.horizontalLayout_inputLayer.setStretch(0, 1)
        self.horizontalLayout_inputLayer.setStretch(1, 3)
        self.horizontalLayout_inputLayer.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_inputLayer)
        self.verticalLayout.addWidget(self.groupBox_inputLayerType)
        self.groupBox_lookupInputs = QtWidgets.QGroupBox(SingleLayerInputDialog)
        self.groupBox_lookupInputs.setObjectName("groupBox_lookupInputs")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_lookupInputs)
        self.verticalLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_lookupTable = QtWidgets.QHBoxLayout()
        self.horizontalLayout_lookupTable.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_lookupTable.setObjectName("horizontalLayout_lookupTable")
        self.label_lookupTable = QtWidgets.QLabel(self.groupBox_lookupInputs)
        self.label_lookupTable.setObjectName("label_lookupTable")
        self.horizontalLayout_lookupTable.addWidget(self.label_lookupTable)
        self.lookup_table_combo = QtWidgets.QComboBox(self.groupBox_lookupInputs)
        self.lookup_table_combo.setObjectName("lookup_table_combo")
        self.horizontalLayout_lookupTable.addWidget(self.lookup_table_combo)
        self.pushButton_browseLookupTable = QtWidgets.QPushButton(self.groupBox_lookupInputs)
        self.pushButton_browseLookupTable.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_browseLookupTable.setObjectName("pushButton_browseLookupTable")
        self.horizontalLayout_lookupTable.addWidget(self.pushButton_browseLookupTable)
        self.horizontalLayout_lookupTable.setStretch(0, 1)
        self.horizontalLayout_lookupTable.setStretch(1, 2)
        self.horizontalLayout_lookupTable.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_lookupTable)
        self.horizontalLayout_mappingField = QtWidgets.QHBoxLayout()
        self.horizontalLayout_mappingField.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_mappingField.setObjectName("horizontalLayout_mappingField")
        self.label_mappingField = QtWidgets.QLabel(self.groupBox_lookupInputs)
        self.label_mappingField.setObjectName("label_mappingField")
        self.horizontalLayout_mappingField.addWidget(self.label_mappingField)
        self.mapping_field_combo = QtWidgets.QComboBox(self.groupBox_lookupInputs)
        self.mapping_field_combo.setObjectName("mapping_field_combo")
        self.horizontalLayout_mappingField.addWidget(self.mapping_field_combo)
        self.horizontalLayout_mappingField.setStretch(0, 5)
        self.horizontalLayout_mappingField.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_mappingField)
        self.horizontalLayout_classField = QtWidgets.QHBoxLayout()
        self.horizontalLayout_classField.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_classField.setObjectName("horizontalLayout_classField")
        self.label_classField = QtWidgets.QLabel(self.groupBox_lookupInputs)
        self.label_classField.setObjectName("label_classField")
        self.horizontalLayout_classField.addWidget(self.label_classField)
        self.class_field_combo = QtWidgets.QComboBox(self.groupBox_lookupInputs)
        self.class_field_combo.setObjectName("class_field_combo")
        self.horizontalLayout_classField.addWidget(self.class_field_combo)
        self.horizontalLayout_classField.setStretch(0, 5)
        self.horizontalLayout_classField.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_classField)
        self.verticalLayout.addWidget(self.groupBox_lookupInputs)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttons = QtWidgets.QDialogButtonBox(SingleLayerInputDialog)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(SingleLayerInputDialog)
        self.buttons.accepted.connect(SingleLayerInputDialog.accept) # type: ignore
        self.buttons.rejected.connect(SingleLayerInputDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SingleLayerInputDialog)

    def retranslateUi(self, SingleLayerInputDialog):
        _translate = QtCore.QCoreApplication.translate
        SingleLayerInputDialog.setWindowTitle(_translate("SingleLayerInputDialog", "Lookup Table"))
        self.label_inputLayer.setText(_translate("SingleLayerInputDialog", "Input Layer:"))
        self.pushButton_browseInputLayer.setToolTip(_translate("SingleLayerInputDialog", "Select Project Folder"))
        self.pushButton_browseInputLayer.setText(_translate("SingleLayerInputDialog", "..."))
        self.groupBox_lookupInputs.setTitle(_translate("SingleLayerInputDialog", "Lookup Inputs"))
        self.label_lookupTable.setText(_translate("SingleLayerInputDialog", "Lookup table:"))
        self.pushButton_browseLookupTable.setToolTip(_translate("SingleLayerInputDialog", "Select Project Folder"))
        self.pushButton_browseLookupTable.setText(_translate("SingleLayerInputDialog", "..."))
        self.label_mappingField.setText(_translate("SingleLayerInputDialog", "Mapping field:"))
        self.label_classField.setText(_translate("SingleLayerInputDialog", "Class field:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SingleLayerInputDialog = QtWidgets.QDialog()
    ui = Ui_SingleLayerInputDialog()
    ui.setupUi(SingleLayerInputDialog)
    SingleLayerInputDialog.show()
    sys.exit(app.exec_())
