title: mHM forcing directories
x-fortran-namelist: directories_mHM
type: object
properties:
  inputFormat_meteo_forcings:
    type: string
    x-fortran-len: buf
    enum: [nc]
    default: nc
  bound_error:
    type: boolean
    default: true
  dir_Precipitation: &domain_directory
    type: array
    items:
      type: string
      x-fortran-len: buf
      format: directory-path
    x-fortran-shape: max_domains
    examples: [[data/master/meteo/pre/]]
  dir_Temperature:
    <<: *domain_directory
    examples: [[data/master/meteo/tavg/]]
  dir_ReferenceET:
    <<: *domain_directory
    examples: [[data/master/meteo/pet/]]
  dir_MinTemperature:
    <<: *domain_directory
    examples: [[data/master/meteo/tmin/]]
  dir_MaxTemperature:
    <<: *domain_directory
    examples: [[data/master/meteo/tmax/]]
  dir_NetRadiation:
    <<: *domain_directory
    examples: [[data/master/meteo/netrad/]]
  dir_absVapPressure:
    <<: *domain_directory
    examples: [[data/master/meteo/eabs/]]
  dir_windspeed:
    <<: *domain_directory
    examples: [[data/master/meteo/windspeed/]]
  dir_Radiation:
    <<: *domain_directory
    examples: [[data/master/meteo/ssrd/]]
  time_step_model_inputs:
    type: array
    items:
      type: integer
      minimum: -3
    x-fortran-shape: max_domains
    examples: [[0]]
