title: mHM output configuration
x-fortran-namelist: NLoutputResults
type: object
properties:
  output_deflate_level:
    type: integer
    minimum: 0
    maximum: 9
    default: 6
  output_double_precision:
    type: boolean
    default: true
  output_time_reference:
    type: integer
    enum: [0, 1, 2]
    default: 0
  timeStep_model_outputs:
    type: integer
    minimum: -3
    default: -2
  outputFlxState:
    type: array
    items:
      type: boolean
    x-fortran-shape: 21
    examples:
      - [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true]
required: [outputFlxState]
