title: Land-cover periods
x-fortran-namelist: LCover
type: object
properties:
  nLCoverScene:
    type: integer
    minimum: 1
    default: 1
  LCoverYearStart:
    type: array
    items:
      type: integer
    x-fortran-shape: max_lcover_scenes
    examples: [[1900]]
  LCoverYearEnd:
    type: array
    items:
      type: integer
    x-fortran-shape: max_lcover_scenes
    examples: [[2100]]
  LCoverfName:
    type: array
    items:
      type: string
      x-fortran-len: buf
      format: file-path
    x-fortran-shape: max_lcover_scenes
    examples: [[lc.asc]]
