title: Time configuration
description: Configuration for mHM 5.13 simulation and evaluation periods.
x-fortran-namelist: config_time
type: object
properties:
  warming_Days:
    type: array
    items:
      type: integer
      x-fortran-kind: i4
      default: 0
      minimum: 0
    x-fortran-shape: max_domains
    title: Warming days
    description: Number of warming days before evaluation for each domain.
  eval_Per:
    type: array
    x-fortran-shape: max_domains
    title: Evaluation periods
    items:
      type: object
      x-fortran-type: eval_period_t
      properties:
        yStart:
          type: integer
          x-fortran-kind: i4
          default: 1990
          title: Start year
        mStart:
          type: integer
          x-fortran-kind: i4
          minimum: 1
          maximum: 12
          default: 1
          title: Start month
        dStart:
          type: integer
          x-fortran-kind: i4
          minimum: 1
          maximum: 31
          default: 1
          title: Start day
        yEnd:
          type: integer
          x-fortran-kind: i4
          default: 1990
          title: End year
        mEnd:
          type: integer
          x-fortran-kind: i4
          minimum: 1
          maximum: 12
          default: 12
          title: End month
        dEnd:
          type: integer
          x-fortran-kind: i4
          minimum: 1
          maximum: 31
          default: 31
          title: End day
  timestep:
    type: array
    items:
      type: integer
      x-fortran-kind: i4
      default: 1
    x-fortran-shape: max_domains
    title: Simulation time step
  share_time_step:
    type: boolean
    default: true
    title: Share time step between domains
