# -*- coding: utf-8 -*-
"""
/***************************************************************************
 pymhmDialog
                                 A QGIS plugin
 Python package for mesoscale Hydrological Model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Sanjeev Bashyal
        email                : sanjeev.bashyal01@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QDialog
from .pymhm_dialog_base import Ui_pymhmDialogBase

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
# FORM_CLASS, _ = uic.loadUiType(os.path.join(
#     os.path.dirname(__file__), 'pymhm_dialog_base.ui'))


class pymhmDialog(QDialog, Ui_pymhmDialogBase):
    def __init__(self, parent=None):
        """Constructor."""
        super(pymhmDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
